[build]
  publish = "www"
  # No real build step - just echo a message
  command = "echo 'No build step - deploying site as-is'"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "www"

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production]
  environment = { NODE_ENV = "production" }

# Deploy Preview context: preview deploys of pull/merge requests
[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

# Branch Deploy context: all branch deploys that don't match
# any of the contexts above
[context.branch-deploy]
  environment = { NODE_ENV = "staging" }

# Headers to set for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://storage.googleapis.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-font 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Cache static assets with long cache times
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  query = { path = ":path" }
  conditions = { Path = { match = "/api/*", negate = true } }

# Domain redirects
[[redirects]]
  from = "https://www.jessesworld.example.com/*"
  to = "https://jessesworld.example.com/:splat"
  status = 301
  force = true

# Old path redirects
[[redirects]]
  from = "/old-page"
  to = "/about"
  status = 301

[[redirects]]
  from = "/legacy-contact"
  to = "/contact"
  status = 301
